version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'  # Важно указать hostname, который будет использоваться для доступа
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222  # Опционально: если нужен нестандартный SSH-порт
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"  # Опционально: если нужен SSH-доступ
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab-network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  gitlab-network:
    external: true
