version: '3.8'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
    networks:
      - gitlab-network
    environment:
      - CI_SERVER_URL=http://gitlab.local/  # Важно: должен совпадать с external_url GitLab
      - REGISTRATION_TOKEN=YOUR_REGISTRATION_TOKEN  # Замените на реальный токен из GitLab
      - RUNNER_NAME=my-runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=alpine:latest
      - DOCKER_NETWORK_MODE=gitlab-network  # Используем ту же сеть, что и GitLab

networks:
  gitlab-network:
    external: true  # Используем уже созданную сеть из gitlab-compose.yml

